name: 'Check README'
on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  check-readme:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'fox-projects/check-organization-links-action'
